### PR TITLE
Move mobile client CRD back because of operator-sdk errors

### PR DESCRIPTION
**Pull request by aliok**
I received an error when the mobile client CRD file was in `deploy/crds`:

```
[aliok@localhost mobile-developer-console-operator]$ operator-sdk generate openapi
INFO[0000] Running OpenAPI code-generation for Custom Resource group versions: [mdc:[v1alpha1], ] 
2019/07/03 12:58:50 Code for OpenAPI definitions generated
W0703 12:58:51.405135   29133 parse.go:239] Ignoring child directory github.com/aerogear/mobile-developer-console-operator/pkg/apis/mdc: No files for pkg "github.com/aerogear/mobile-developer-console-operator/pkg/apis/mdc"
Error: no API exists for Group mobile Version v1alpha1 Kind MobileClient
Usage:
  operator-sdk generate openapi [flags]

Flags:
  -h, --help   help for openapi

Global Flags:
      --verbose   Enable verbose logging
```

Don't know what operator-sdk is trying to do with that file, but lets move it back.

Here's the output after I move:
```
[aliok@localhost mobile-developer-console-operator]$ operator-sdk generate openapi
INFO[0000] Running OpenAPI code-generation for Custom Resource group versions: [mdc:[v1alpha1], ] 
2019/07/03 13:00:35 Code for OpenAPI definitions generated
W0703 13:00:36.418061   29706 parse.go:239] Ignoring child directory github.com/aerogear/mobile-developer-console-operator/pkg/apis/mdc: No files for pkg "github.com/aerogear/mobile-developer-console-operator/pkg/apis/mdc"
INFO[0002] Created deploy/crds/mdc_v1alpha1_mobiledeveloperconsole_crd.yaml 
INFO[0002] Code-generation complete.                    
```

@laurafitzgerald I didn't really do any verification for https://github.com/aerogear/mobile-developer-console-operator/pull/6 as I though "what can go wrong?" :) but something did :)

The reason that Travis didn't fail is because we don't have `operator-sdk generate openapi` command in our Makefile. I will add that in another PR (one [this](https://github.com/aerogear/unifiedpush-operator/pull/35) merged in UPS I will copy stuff from there).

### CODE REVIEW

**Review by laurafitzgerald — APPROVED** [review]
@aliok approved. Sorry I also missed that.

**Comment by grdryn** [comment]
@aliok huh, that's odd, it works for me in the other operator projects when the crd yaml files are in that `/deploy/crds/` directory. What version of the operator-sdk do you see the error with?

Generally speaking though, this looks fine to me :slightly_smiling_face:

**Comment by aliok** [comment]
The thing is that CRD is not generated by the operator. That's the mobile client CRD which MDC server uses. Other CRDs used/generated by the operator still has to live in `deploy/crds`

**Comment by grdryn** [comment]
@aliok ah right, I misunderstood then. :+1:  I presume that the MobileClient CRD here then is just used for testing, is it? On the cluster the actual CRD should be added when the actual operator that handles it is added, right?

**Comment by aliok** [comment]
> On the cluster the actual CRD should be added when the actual operator that handles it is added, right?

I thought we would install it manually. Don't have a strong opinion though.

Installing by operator --> sounds good. But, I guess we can't really watch the CRD definition itself for changes etc. Or, can we? Sounds strange for a reason although it is just another resource.

Similar question: why operators don't install their own (as in androidVariant in UPS) CRDs?

@grdryn

**Comment by odra** [comment]
It requires cluster access to do so and the operator sdk is structured in a way that it needs those crds already defined when you watch a specific resource, which is why OLM installs the required crds for your operator.

**Comment by aliok** [comment]
Some more discussion here: https://chat.google.com/room/AAAA_u92fRU/s_-i-iqmjss

**Pull request merged**
