### PR TITLE
⬆ Upgrade to operator-sdk v0.10.0

### PR DESCRIPTION
**Pull request by grdryn**
JIRA: https://issues.jboss.org/browse/AEROGEAR-9984

----

## Verification Setup
- [x] Install application monitoring stack from [here](https://github.com/integr8ly/application-monitoring-operator/)
- [x] `sed -i -e "s/master/PR-57/" deploy/operator.yaml`
- [x] Wait for "continuous-integration/jenkins/pr-merge" status check to pass

_Fresh install_
- [x] `make cluster/prepare install-operator install-mdc`

_Upgrade_
- [x] `sed -i -e "s/master/PR-57/" deploy/operator.yaml`
- [x] `kubectl apply -f deploy/role.yaml`
- [x] `kubectl apply -f deploy/operator.yaml`

## Verification steps:
- [x] Check that there are no errors in the operator pod
- [x] Verify that there's a ServiceMonitor called `mobile-developer-console-operator-metrics`, and it's labelled "monitoring-key=middleware"
- [x] Verify that the operator metrics are showing up in Prometheus. This query should be sufficient, assuming you've got a MobileDeveloperConsole CR applied:
image

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
👀

**Comment by laurafitzgerald** [comment]
**Verification**
I've verified the installation side of things. It all works as expected.
@jomrazek is going to continue with verifying the upgrade one.

**Review by jomrazek — APPROVED** [review]
update and also installation are working as expected for me too

**Comment by grdryn** [comment]
Thanks for the reviews and verifications folks! :pray:

**Pull request merged**
